config/routes.rb
SampleAssociation::Application.routes.draw do
  resources :employees do 
	  collection do 
		    get :employee_autocomplete
	  end
	  member do 
		 get :employee_autocomplete
	  end
  end
  resources :articles
  resources :comments
  resources :events
  resources :photos

   root :to => 'employees#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_protected
  has_many :comments, :as => :commentable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_protected
  belongs_to :commentable, :polymorphic => true
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :manager_id, :name
   has_many :employee_list, class_name: "Employee", foreign_key: "manager_id" 
   belongs_to :manager, class_name: "Employee"
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_protected
  has_many :comments, :as => :commentable
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_protected
  has_many :comments, :as => :commentable 
  has_attached_file :image,
                  :url  => "/assets/photos/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/photos/:id/:style/:basename.:extension"
		  
  validates_attachment_content_type :image, :content_type => /image/ 
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.find(:all)
  end
  
  def show
    @article = Article.find(params[:id])
    @comment = Comment.new(:commentable => @article)
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(params[:article])
    if @article.save
      flash[:notice] = "Successfully created article."
      redirect_to @article
    else
      render :action => 'new'
    end
  end
  
  def edit
    @article = Article.find(params[:id])
  end
  
  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
      flash[:notice] = "Successfully updated article."
      redirect_to @article
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:notice] = "Successfully destroyed article."
    redirect_to articles_url
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @commentable = find_commentable
    @comments = @commentable.comments
  end
  
  def show
    @comment = Comment.find(params[:id])
  end
  
  def new
    @comment = Comment.new
  end
  
  def create
   @commentable = find_commentable
   puts @commentable.inspect
    @comment = @commentable.comments.build(params[:comment])
    if @comment.save
      flash[:notice] = "Successfully created comment."
      redirect_to :id => nil
    else
      render :action => 'new'
    end
  end
  
  def edit
    @comment = Comment.find(params[:id])
  end
  
  def update
    @comment = Comment.find(params[:id])
    if @comment.update_attributes(params[:comment])
      flash[:notice] = "Successfully updated comment."
      redirect_to @comment
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:notice] = "Successfully destroyed comment."
    redirect_to comments_url
  end
  
  private
  
  def find_commentable
	  puts params
    params.each do |name, value|
      if name =~ /(.+)_id$/
        return $1.classify.constantize.find(value)
      end
    end
    nil
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
    @employee_list = Employee.where("manager_id is null")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
    end
  end
  
  def employee_autocomplete
    employee = Employee.where("name like '#{params[:term]}%'")
    employee_auto =   employee.blank? ? []: employee.collect{|i|i.name}    
    render :json => employee_auto
end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employees = Employee.where("name != 'CEO' and manager_id is null")
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])
    @employee.manager_id = Employee.find_by_name(params[:employee][:manager_id]).id
    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
	params[:employee][:manager_id] = Employee.find_by_name(params[:employee][:manager_id]).id
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end
  
  def show
    @event = Event.find(params[:id])
  end
  
  def new
    @event = Event.new
  end
  
  def create
    @event = Event.new(params[:event])
    if @event.save
      flash[:notice] = "Successfully created event."
      redirect_to @event
    else
      render :action => 'new'
    end
  end
  
  def edit
    @event = Event.find(params[:id])
  end
  
  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(params[:event])
      flash[:notice] = "Successfully updated event."
      redirect_to @event
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    flash[:notice] = "Successfully destroyed event."
    redirect_to events_url
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all.reverse
  end
  
  def show
    @photo = Photo.find(params[:id])
  end
  
  def new
    @photo = Photo.new
  end
  
  def create
    @photo = Photo.new(params[:photo])
    if @photo.save
      flash[:notice] = "Successfully created photo."
      redirect_to @photo
    else
      render :action => 'new'
    end
  end
  
  def edit
    @photo = Photo.find(params[:id])
  end
  
  def update
    @photo = Photo.find(params[:id])
    if @photo.update_attributes(params[:photo])
      flash[:notice] = "Successfully updated photo."
      redirect_to @photo
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    flash[:notice] = "Successfully destroyed photo."
    redirect_to photos_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/articles/_form.html.erb
<%#= error_messages_for :article %>
<%= form_for @article do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.label :author_name %><br />
    <%= f.text_field :author_name %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/articles/edit.html.erb
<%# title "Edit Article" %>

<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", @article %> |
  <%= link_to "View All", articles_path %>
</p>

app/views/articles/index.html.erb
<%# title "Articles" %>

<div id="articles">
<% for article in @articles %>
  <h2>
    <%= link_to h(article.name), article %>
  </h2>
  <div class="author">from <%=h article.author_name %> on <%= article.created_at.strftime('%b %d, %Y') %></div>
  <div class="content"><%= simple_format(article.content) %></div>
<% end %>
</div>
<p><%= link_to "New Article", new_article_path %></p>

app/views/articles/new.html.erb
<%# title "New Article" %>

<%= render :partial => 'form' %>

<p><%= link_to "Back to List", articles_path %></p>

app/views/articles/show.html.erb
<%# title @article.name %>

<p class="author"><em>from <%=h @article.author_name %></em></p>

<%=simple_format @article.content %>

<p><%= link_to "Back to Articles", articles_path %></p>

<% unless @article.comments.empty? %>
  <h2><%= pluralize(@article.comments.size, 'comment') %></h2>

  <div id="comments">
  <% for comment in @article.comments %>
    <div class="comment">
      <strong><%= link_to_unless comment.site_url.blank?, h(comment.author_name), h(comment.site_url) %></strong>
      <em>on <%= comment.created_at.strftime('%b %d, %Y at %H:%M') %></em>
      <%=simple_format comment.content %>
    </div>
  <% end %>
  </div>
<% end %>

<h3>Add your comment:</h3>
<%= render :partial => 'comments/form' %>

app/views/comments/_form.html.erb
<%= form_for [@commentable, @comment] do |f| %>
  <%#= f.error_messages %>
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/comments/edit.html.erb
<%# title "Edit Comment" %>

<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", @comment %> |
  <%= link_to "View All", comments_path %>
</p>

app/views/comments/index.html.erb
<%# title "Comments" %>

<div id="comments">
<% for comment in @comments %>
  <div class="comment">
    <%=simple_format comment.content %>
  </div>
<% end %>
</div>


<h2>New Comment</h2>

<% form_for [@commentable, Comment.new] do |f| %>
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/comments/new.html.erb
<%# title "New Comment" %>

<%= render :partial => 'form' %>

<p><%= link_to "Back to List", comments_path %></p>

app/views/comments/show.html.erb
<%# title "Comment" %>

<p>
  <strong>Content:</strong>
  <%=h @comment.content %>
</p>
<p>
  <strong>Commentable:</strong>
  <%=h @comment.commentable_id %>
</p>
<p>
  <strong>Commentable Type:</strong>
  <%=h @comment.commentable_type %>
</p>

<p>
  <%= link_to "Edit", edit_comment_path(@comment) %> |
  <%= link_to "Destroy", @comment, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", comments_path %>
</p>

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="ui-widget">
  <label for="tags">Manager Name: </label>
  <%= f.text_field :manager_id %>  
</div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
  <%= stylesheet_link_tag 'jquery-ui' %>
    <%= javascript_include_tag 'jquery-1.9.1','
jquery-ui' %>
<script>
  $(function() {
    
    $( "#employee_manager_id" ).autocomplete({
         source: "employee_autocomplete"
    });
  });
  </script>
</head>
<body>
 

 

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>

<div>
<%@employees.each do |i|%>
<%if !i.employee_list.blank?%>
     <ul>     
     <li>
     <%= i.name%>
		 
		  <%i.employee_list.each do |k|%>
			<ul>
		 <li>
		   <%= k.name%>
		 </li>
		 </ul>
		 <%end%>
     </li>
		
     </ul>
     <%end%>
<%end%>
</div>

<br />

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @employee.name %>
</p>

<p>
  <b>Manager:</b>
  <%= @employee.manager_id %>
</p>


<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
  <%#= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :starts_at %><br />
    <%= f.datetime_select :starts_at %>
  </p>
  <p>
    <%= f.label :ends_at %><br />
    <%= f.datetime_select :ends_at %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/events/edit.html.erb
<%# title "Edit Event" %>

<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", @event %> |
  <%= link_to "View All", events_path %>
</p>

app/views/events/index.html.erb
<%# title "Events" %>

<% for event in @events %>
  <div class="event">
    <h3><%=h event.name %></h3>
    <div class="date">From <%= event.starts_at.strftime("%B %d, %Y") %> to <%= event.ends_at.strftime("%B %d, %Y") %></div>
    <div><%=h event.description %></div>
  </div>
<% end %>

<p><%= link_to "New Event", new_event_path %></p>

app/views/events/new.html.erb
<%# title "New Event" %>

<%= render :partial => 'form' %>

<p><%= link_to "Back to List", events_path %></p>

app/views/events/show.html.erb
<%# title "Event" %>

<p>
  <strong>Name:</strong>
  <%=h @event.name %>
</p>
<p>
  <strong>Starts At:</strong>
  <%=h @event.starts_at %>
</p>
<p>
  <strong>Ends At:</strong>
  <%=h @event.ends_at %>
</p>
<p>
  <strong>Description:</strong>
  <%=h @event.description %>
</p>

<p>
  <%= link_to "Edit", edit_event_path(@event) %> |
  <%= link_to "Destroy", @event, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", events_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title><%#= h(yield(:title) || "Untitled") %></title>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application' %>
    <%#= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <div id="nav">
        <%= link_to "Articles", articles_path %> |
        <%= link_to "Photos", photos_path %> |
        <%= link_to "Events", events_path %>
      </div>
      
      <%- flash.each do |name, msg| -%>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <%- end -%>
      
      <%#- if show_title? -%>
        <h1><%#=h yield(:title) %></h1>
      <%#- end -%>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_for @photo, :html => { :multipart => true } do |f| %>
  <%#= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/photos/edit.html.erb
<%# title "Edit Photo" %>

<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", @photo %> |
  <%= link_to "View All", photos_path %>
</p>

app/views/photos/index.html.erb
<%# title "Photos" %>

<% for photo in @photos %>
  <div class="photo">
    <%= image_tag photo.image.url(:original) %>
    <p><%=h photo.name %></p>
  </div>
<% end %>

<p><%= link_to "New Photo", new_photo_path %></p>

app/views/photos/new.html.erb
<%# title "New Photo" %>

<%= render :partial => 'form' %>

<p><%= link_to "Back to List", photos_path %></p>

app/views/photos/show.html.erb
<%# title "Photo" %>

<p>
  <strong>Name:</strong>
  <%=h @photo.name %>
</p>

<p>
  <%= link_to "Edit", edit_photo_path(@photo) %> |
  <%= link_to "Destroy", @photo, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", photos_path %>
</p>